apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - image: mu2729/streaming-subscriptions
        name: subscriptions
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_HTTP_PORT
          value: 8080
#        - name: KUMULUZEE_SERVER_BASE-URL
#          value: http://159.122.186.127:8082
#        - name: KUMULUZEE_DATASOURCES0_CONNECTION-URL
#          value: jdbc:postgresql://192.168.99.100:5432/streaming
        ports:
        - containerPort: 8080
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: subscriptions
spec:
  type: NodePort
  selector:
      app: subscriptions
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080